### PR TITLE
Move guix to linux folder

### PR DESCRIPTION
**Pull request by brejoc**
Since Guix is a Linux distribution, it should be in the linux folder.

### CODE REVIEW

**Comment by brejoc** [comment]
@sawanoboly Does that make sense to you too?

**Review by sawanoboly — CHANGES_REQUESTED** [review]
@brejoc 

I didn't know much about guix so I looked it up.
I think it would be better to classify those whose default kernel is Linux-libre as a separate category.
Instead of putting them in the linux folder, how about creating a new `Linux-libre` folder and moving them there?

**Comment by brejoc** [comment]
That's kind of the old debate about Linux vs GNU/Linux, aso. I don't really have a strong opinion on that. Sure, we can move it `linux-libre`.

**Review by sawanoboly — APPROVED** [review]
👍

**Pull request merged**
