### PR TITLE
Adds release files for Fedora 31 Workstation

### PR DESCRIPTION
**Pull request by brejoc**

### CODE REVIEW

**Comment by sawanoboly** [comment]
thanks 😃

**Comment by brejoc** [comment]
Woops. I've just noticed that the commit message for the README was wrong. Should have been 31 instead of 30. Oh, well. Thanks for merging!

**Comment by sawanoboly** [comment]
@brejoc 
I'll grant you commit rights to this repository if you like, but what do you think?

**Comment by brejoc** [comment]
@sawanoboly That would be cool. Thanks!

**Pull request merged**
