### PR TITLE
Adds latest Ubuntu, and adds a Linux Mint Version

### PR DESCRIPTION
**Pull request by svengeance**
This repo was very helpful, and I hadn't discovered it until [after I had manually acquired this myself!](https://blog.sven.ai/linux-distribution-os-release-information-compilation/). Thank you for the effort - I'm trying to give back some of the differences.

Let me know if anything needs changed.

### CODE REVIEW

**Review by brejoc — APPROVED** [review]
Thanks a lot for your contribution! Looks good to me!

**Review by brejoc — CHANGES_REQUESTED** [review]
Oh, wait a second. Sorry, I overlooked something. Would you be able to also add `lsb-release` and `debian_version`?

**Comment by svengeance** [comment]
Added as requested - unfortunately I don't have a copy of linux mint myself to run these commands - I sourced the data from an article that listed out the content of os-release. If you'd like me to remove if it's incomplete, not an issue

**Review by brejoc — APPROVED** [review]
Great! Thanks a lot! 👍

**Pull request merged**
