### PR TITLE
Adds release files for Fedora 32 Workstation

### PR DESCRIPTION
**Pull request by brejoc**
Also adds it to the README

### CODE REVIEW

**Comment by sawanoboly** [comment]
@brejoc

Hi,
I've invited you as a Write-authorized user of this Repository. Please try to merge this pull requests for starters, if you like.

**Comment by brejoc** [comment]
@sawanoboly I didn't get an invitation and I can't merge this PR. Maybe a typo?

**Comment by sawanoboly** [comment]
Manage access 2020-04-18 21-13-39

hmm... I've resend invitation. Pelase check a mailbox.

**Comment by brejoc** [comment]
@sawanoboly Finally! I found it! Was in the spam folder of my work email. 😩

**Pull request merged**
